table 'Dim Specialty'
	lineageTag: a102407d-3b93-424a-be12-96511a297e81

	column 'Specialty Code'
		dataType: string
		isKey
		lineageTag: 6562bbd1-fffe-48a5-9f18-44517c5c44ad
		summarizeBy: none
		sourceColumn: Specialty Code

	column 'Specialty Name'
		dataType: string
		lineageTag: c9e2b0bd-9ded-4a94-b262-fb103c9f89a3
		summarizeBy: none
		sourceColumn: Specialty Name

	partition 'Dim Specialty' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(CuratedDataFolder & "\dim_specialty.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"Specialty Code", type text}, {"Specialty Name", type text}}, "en-GB")
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

